version: "3.8"

services:
  wordpress_en:
    container_name: pingcap_website_en_env_php_apache
    image: wordpress:php8.1-apache
    restart: always
    ports:
      - ${WEBSITE_EN_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: pingcap
      WORDPRESS_DB_PASSWORD: pingcap
      WORDPRESS_DB_NAME: pingcap_website_en
    volumes:
      - ${WEBSITE_EN_SRC}/pingcap:/var/www/html/wp-content/themes/pingcap
      - ${WEBSITE_EN_SRC}/wp-content/plugins:/var/www/html/wp-content/plugins
      - ${WEBSITE_EN_SRC}/wp-content/uploads:/var/www/html/wp-content/uploads
      - ${WEBSITE_EN_SRC}/wp-content/.htaccess:/var/www/html/.htaccess

  wordpress_cn:
    container_name: pingcap_website_cn_env_php_apache
    image: wordpress:php8.1-apache
    restart: always
    ports:
      - ${WEBSITE_CN_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: pingcap
      WORDPRESS_DB_PASSWORD: pingcap
      WORDPRESS_DB_NAME: pingcap_website_cn
    volumes:
      - ${WEBSITE_CN_SRC}:/var/www/html/wp-content/themes/pingcap
      - ${WEBSITE_CN_SRC}/wp-content/plugins:/var/www/html/wp-content/plugins
      - ${WEBSITE_CN_SRC}/wp-content/uploads:/var/www/html/wp-content/uploads

  mysql:
    container_name: pingcap_website_mysql
    image: mysql:5.7
    restart: always
    ports:
      - ${WEBSITE_MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: pingcap_website_en
      MYSQL_USER: pingcap
      MYSQL_PASSWORD: pingcap
      MYSQL_ROOT_PASSWORD: pingcap
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
