version: "3.8"

services:
  wordpress_en:
    container_name: pingcap_website_en_env_php_apache
    image: wordpress:php8.1-apache
    restart: always
    ports:
      - ${WEBSITE_EN_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: pingcap
      WORDPRESS_DB_PASSWORD: pingcap
      WORDPRESS_DB_NAME: pingcap_website_en
    volumes:
      - ${WEBSITE_EN_SRC}/pingcap:/var/www/html/wp-content/themes/pingcap
      - ${WEBSITE_EN_SRC}/pingcap/.htaccess:/var/www/html/.htaccess
      - ${WEBSITE_EN_SRC}/wp-content/plugins:/var/www/html/wp-content/plugins
      - ${WEBSITE_EN_SRC}/wp-content/uploads:/var/www/html/wp-content/uploads

  wordpress_cn:
    container_name: pingcap_website_cn_env_php_apache
    image: wordpress:php8.1-apache
    restart: always
    ports:
      - ${WEBSITE_CN_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: pingcap
      WORDPRESS_DB_PASSWORD: pingcap
      WORDPRESS_DB_NAME: pingcap_website_cn
    volumes:
      - ${WEBSITE_CN_SRC}/pingcap-cn:/var/www/html/wp-content/themes/pingcap-cn
      - ${WEBSITE_CN_SRC}/pingcap-cn/.htaccess:/var/www/html/.htaccess
      - ${WEBSITE_CN_SRC}/wp-content/plugins:/var/www/html/wp-content/plugins
      - ${WEBSITE_CN_SRC}/wp-content/uploads:/var/www/html/wp-content/uploads

  wordpress_jp:
    container_name: pingcap_website_jp_env_php_apache
    image: wordpress:php8.1-apache
    restart: always
    ports:
      - ${WEBSITE_JP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: pingcap
      WORDPRESS_DB_PASSWORD: pingcap
      WORDPRESS_DB_NAME: pingcap_website_jp
      # WORDPRESS_DB_HOST: ${TIDB_HOST}:${TIDB_PORT}
      # WORDPRESS_DB_NAME: ${TIDB_DB_NAME}
      # WORDPRESS_DB_PASSWORD: ${TIDB_PASSWORD}
      # WORDPRESS_DB_USER: ${TIDB_USER}
      # WORDPRESS_DB_COLLATE: utf8mb4_bin
      # WORDPRESS_CONFIG_EXTRA: |
      #   define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);
      #   define('MYSQL_SSL_CA', '/etc/ssl/certs/ca-certificates.crt');
    volumes:
      - ${WEBSITE_JP_SRC}/pingcap-jp:/var/www/html/wp-content/themes/pingcap-jp
      - ${WEBSITE_JP_SRC}/pingcap-jp/.htaccess:/var/www/html/.htaccess
      - ${WEBSITE_JP_SRC}/wp-content/plugins:/var/www/html/wp-content/plugins
      - ${WEBSITE_JP_SRC}/wp-content/uploads:/var/www/html/wp-content/uploads

  mysql:
    container_name: pingcap_website_mysql
    image: mysql:5.7
    restart: always
    ports:
      - ${WEBSITE_MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: pingcap_website_en
      MYSQL_USER: pingcap
      MYSQL_PASSWORD: pingcap
      MYSQL_ROOT_PASSWORD: pingcap
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-dev/conf.d:/etc/nginx/conf.d
